name: Test System Integration
on:
  push:
  workflow_dispatch:
      
jobs:
  build:
    runs-on: Ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/checkout@v4
      with:
        repository: DevOpsTeamE/DevOps2023Asg1_Test
        token: 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
        path: tests
    - name: Move files to root
      run: |
        mv ./tests/*.py ./
        mv ./tests/*.sql ./
        rm -rf tests

    - name: Show directory
      run: | 
        ls -l
        mkdir artifacts
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install Flask
        python -m pip install mysql-connector-python
    - name: Setup database
      run: |
        sudo apt update
        sudo apt install mysql-server
        sudo systemctl start mysql.service
        sudo systemctl status mysql.service
        sudo mysql --user=root --password=root < database_setup.sql
        sudo mysql --user=root --password=root < test_credentials.sql
        
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
    - name: Upload pytest test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: junit/test-results.xml

    - name: Deploy SIT
      continue-on-error: true
      if: success()
      uses: appleboy/ssh-action@v0.1.10
      with:
        host:  ${{ secrets.HOSTNAME }}
        username: joshuang321_gmail_com
        passphrase: ihatedevops
        key: ${{ secrets.KEY }}
        port: 22
        command_timeout: 30m
        script: | 
          sudo rm -rf *;git clone https://joshuang321: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@github.com/DevOpsTeamE/DevOps2023Asg1; sudo bash ~/DevOps2023Asg1/setup.sh; gunicorn -w 4 'main:create_app()';